cmd/kms-rest/go.sum
go.mod
go.sum
pkg/keystore/service.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_test.go
test/bdd/bddtests_test.go
test/bdd/features/keystore_api.feature
test/bdd/features/kms_api.feature
test/bdd/pkg/common/common_steps.go
test/bdd/pkg/context/context.go
test/bdd/pkg/healthcheck/healthcheck_steps.go
test/bdd/pkg/keystore/keystore_steps.go
test/bdd/pkg/kms/kms_steps.go

test: add BDD test for "create key" API

---

cmd/kms-rest/startcmd/start.go
cmd/kms-rest/startcmd/start_test.go
test/bdd/features/healthcheck_api.feature
test/bdd/features/keystore_api.feature
test/bdd/features/kms_api.feature
test/bdd/fixtures/kms-rest/docker-compose.yml
test/bdd/pkg/bddutil/bddutil.go
test/bdd/pkg/common/common_steps.go
test/bdd/pkg/healthcheck/healthcheck_steps.go
test/bdd/pkg/keystore/keystore_steps.go
test/bdd/pkg/kms/kms_steps.go

feat: implement TLS support

---

cmd/kms-rest/startcmd/start.go
go.mod
go.sum
pkg/kms/service.go
pkg/kms/service_test.go
pkg/restapi/kms/controller_test.go
pkg/restapi/kms/operation/models.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_test.go
test/bdd/features/kms_api.feature
test/bdd/pkg/kms/kms_steps.go

feat: implement API for Sign operation

---

go.mod
pkg/kms/service.go
pkg/kms/service_test.go
pkg/restapi/kms/controller_test.go
pkg/restapi/kms/operation/models.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_test.go
scripts/check_integration.sh
test/bdd/bddtests_test.go
test/bdd/features/kms_api.feature
test/bdd/pkg/kms/kms_steps.go

feat: implement API for Verify operation

---

cmd/kms-rest/go.mod
cmd/kms-rest/go.sum
go.mod
go.sum
pkg/keystore/repository.go

Update edge-core dependency (includes trustbloc/edge-core#52, trustbloc/edge-core#55)
Signed-off-by: Derek Trider <Derek.Trider@securekey.com>

chore: Update edge-core dependency

---

README.md
docs/build.md
docs/kms_rest_cli.md
docs/kms_rest_docker.md

docs: document basic usage and prerequisites

---

cmd/kms-rest/startcmd/start.go
cmd/kms-rest/startcmd/start_test.go

fix: make TLS optional

---

ci/version_var.sh
cmd/kms-rest/go.mod
cmd/kms-rest/go.sum
go.mod
go.sum

chore: Release v0.1.4

---

ci/version_var.sh

chore: complete Release v0.1.4

---

pkg/kms/error.go
pkg/kms/error_test.go
pkg/kms/service.go
pkg/kms/service_test.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_test.go

refactor: error handling

---

pkg/internal/common/httphandler.go
pkg/internal/mock/keystore/mock_repository.go
pkg/internal/mock/kms/mock_provider.go
pkg/keystore/repository.go
pkg/keystore/repository_test.go
pkg/kms/service.go
pkg/restapi/healthcheck/operation/operations.go
pkg/restapi/kms/operation/mock_provider.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_test.go
scripts/check_lint.sh

chore: enable linter for code within pkg

---

cmd/kms-rest/startcmd/start.go
cmd/kms-rest/startcmd/start_test.go
pkg/keystore/repository.go
pkg/keystore/repository_test.go
test/bdd/bddtests_test.go

refactor: delay store initialization until the first usage

---

.golangci.yml
cmd/kms-rest/main.go
cmd/kms-rest/startcmd/start.go
cmd/kms-rest/startcmd/start_test.go
pkg/kms/error.go
pkg/kms/error_test.go
pkg/kms/service.go
pkg/restapi/kms/operation/operations.go
scripts/check_integration.sh
scripts/check_lint.sh
scripts/check_unit.sh
scripts/generate_test_keys.sh
test/bdd/bddtests_test.go
test/bdd/dockerutil/compose.go
test/bdd/dockerutil/docker.go
test/bdd/pkg/bddutil/bddutil.go
test/bdd/pkg/common/common_steps.go
test/bdd/pkg/context/context.go
test/bdd/pkg/healthcheck/healthcheck_steps.go
test/bdd/pkg/keystore/keystore_steps.go
test/bdd/pkg/kms/kms_steps.go

chore: update testpackage, whyNoLint and logger linter options

---

pkg/internal/mock/kms/mock_service.go
pkg/kms/error.go
pkg/kms/service.go
pkg/kms/service_test.go
pkg/restapi/kms/controller_test.go
pkg/restapi/kms/operation/models.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_test.go
test/bdd/features/keystore_api.feature
test/bdd/features/kms_api.feature
test/bdd/pkg/keystore/keystore_steps.go
test/bdd/pkg/kms/kms_steps.go

feat: export public key API

---

cmd/kms-rest/go.sum
cmd/kms-rest/startcmd/start.go
cmd/kms-rest/startcmd/start_test.go
scripts/generate_test_keys.sh
test/bdd/fixtures/kms/docker-compose.yml

feat: implement secretlock for Keystore KMS

---

pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_test.go
test/bdd/features/kms_api.feature
test/bdd/fixtures/kms/docker-compose.yml
test/bdd/pkg/common/common_steps.go
test/bdd/pkg/context/context.go
test/bdd/pkg/kms/steps.go
test/bdd/pkg/kms/user.go

chore: add authz-kms to bdd test

---

pkg/restapi/kms/operation/models.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_test.go
test/bdd/pkg/kms/models.go
test/bdd/pkg/kms/steps.go

feat: sync up operations payload with Aries remote kms/crypto

---

cmd/kms-rest/startcmd/start.go
go.mod
pkg/auth/zcapld/service.go
pkg/auth/zcapld/service_test.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_test.go
pkg/storage/edv/edvstorage.go
pkg/storage/edv/edvstorage_test.go
test/bdd/features/keystore_api.feature
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/keystore/keystore_steps.go

feat: create and return zcap when creating new keystore

---

cmd/kms-rest/startcmd/start.go

fix: add MethodOptions to cors

---

pkg/secretlock/secretsplitlock/secret_split_lock.go
pkg/secretlock/secretsplitlock/secret_split_lock_test.go

fix: decoding secret from the header

---

cmd/kms-rest/go.mod
cmd/kms-rest/go.sum
go.mod
go.sum
test/bdd/fixtures/edv/.env
test/bdd/go.mod
test/bdd/go.sum

chore: update edv and edge-core revision

---

scripts/generate_test_keys.sh
test/bdd/bddtests_test.go
test/bdd/features/keystore_api.feature
test/bdd/features/kms_api.feature
test/bdd/fixtures/oathkeeper/config/auth-keyserver/config.yaml
test/bdd/fixtures/oathkeeper/config/auth-keyserver/rules/resource-server.json
test/bdd/fixtures/oathkeeper/config/ops-keyserver/config.yaml
test/bdd/fixtures/oathkeeper/config/ops-keyserver/rules/resource-server.json
test/bdd/fixtures/oathkeeper/docker-compose.yml
test/bdd/pkg/keystore/keystore_steps.go
test/bdd/pkg/kms/auth_edv_steps.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/user.go

Signed-off-by: George Aristy <george.aristy@securekey.com>

test: add oathkeeper to BDD tests

---

pkg/internal/mock/kms/mock_crypto_box.go
pkg/internal/mock/kms/mock_provider.go
pkg/internal/mock/kms/mock_service.go
pkg/kms/creator.go
pkg/kms/error.go
pkg/kms/service.go
pkg/kms/service_cryptobox.go
pkg/kms/service_cryptobox_test.go
pkg/kms/service_test.go
pkg/restapi/kms/operation/middleware.go
pkg/restapi/kms/operation/models.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_cryptobox.go
pkg/restapi/kms/operation/operations_cryptobox_test.go
pkg/restapi/kms/operation/operations_test.go

Part of #117.
BDD tests will come in a separate PR.

feat: add support for CryptoBox operations

---

pkg/restapi/kms/operation/operations_cryptobox_test.go
test/bdd/features/kms_crypto_box_api.feature
test/bdd/pkg/kms/auth_edv_steps.go
test/bdd/pkg/kms/kms_crypto_box_steps.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/models.go
test/bdd/pkg/kms/user.go
test/bdd/pkg/kms/zcap.go

test: add BDD test for SealOpen CryptoBox operation

---

cmd/kms-rest/startcmd/start.go
cmd/kms-rest/startcmd/start_prepare_kms.go
cmd/kms-rest/startcmd/start_prepare_secretlock.go
go.sum
pkg/secretlock/secretsplitlock/secret_split_lock.go
pkg/secretlock/secretsplitlock/secret_split_lock_test.go
test/bdd/fixtures/kms/docker-compose.yml

closes #126
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

feat: cache HTTP calls for fetching secret shares

---

cmd/kms-rest/startcmd/start_prepare_kms.go
pkg/kms/creator.go
pkg/kms/creator_test.go
test/bdd/go.sum

This is an emergency solution and will be updated in https://github.com/trustbloc/hub-kms/issues/134.

feat: add caching to service creator

---

pkg/restapi/kms/operation/operations.go

- Removed httpdump and added only url in the log
Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

refactor: input request logger

---

cmd/kms-rest/startcmd/lddocument_loader.go
cmd/kms-rest/startcmd/start.go
pkg/restapi/kms/operation/middleware.go
pkg/restapi/kms/operation/operations.go

Signed-off-by: George Aristy <george.aristy@securekey.com>

fix: zcap middleware: missing cached JSONLD contexts

---

ci/version_var.sh

chore: complete Release v0.1.5

---

cmd/kms-rest/go.mod
cmd/kms-rest/go.sum
go.mod
go.sum
test/bdd/go.mod
test/bdd/go.sum

chore: update aries dependency and remove forks

---

Makefile
ci/azure-pipelines.yml
ci/version_var.sh
docs/kms_rest_docker.md
test/bdd/fixtures/edv/.env
test/bdd/fixtures/kms/.env
test/bdd/fixtures/openapi-demo/.env

Signed-off-by: Troy Ronda <troy.ronda@securekey.com>

ci: migrate to ghcr

---

README.md
ci/azure-pipelines.yml
images/kms-rest/Dockerfile
test/bdd/fixtures/auth/.env

Signed-off-by: Troy Ronda <troy.ronda@securekey.com>

chore: add docker label for github repo

---

README.md
ci/azure-pipelines.yml

Signed-off-by: Troy Ronda <troy.ronda@securekey.com>

chore: change master branch to main

---

cmd/kms-rest/go.mod
cmd/kms-rest/go.sum
go.mod
go.sum
test/bdd/go.mod
test/bdd/go.sum
test/bdd/mock/loginconsent/go.mod
test/bdd/mock/loginconsent/go.sum

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

chore: Updates edge-core revision

---

cmd/kms-rest/startcmd/start.go
pkg/internal/mock/keystore/mock_keystore.go
pkg/keystore/keystore.go
pkg/keystore/keystore_test.go
pkg/restapi/kms/operation/middleware.go
pkg/restapi/kms/operation/middleware_test.go
pkg/restapi/kms/operation/models.go
pkg/restapi/kms/operation/openapi.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_test.go
test/bdd/bddtests_test.go
test/bdd/features/kms_api.feature
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/models.go
test/bdd/pkg/kms/zcap.go

feat: implement API for importing private key

---

cmd/kms-rest/go.mod
cmd/kms-rest/go.sum

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

chore: Updates couchdb revision

---

pkg/restapi/kms/operation/middleware.go
pkg/restapi/kms/operation/middleware_test.go
pkg/restapi/kms/operation/models.go
pkg/restapi/kms/operation/openapi.go
pkg/restapi/kms/operation/operations.go
pkg/restapi/kms/operation/operations_bbs_test.go

BDD tests will be added in https://github.com/trustbloc/kms/issues/172.
Closes #167

feat: implement API for BBS+ crypto

---

ci/version_var.sh

chore: complete Release v0.1.6

---

pkg/secretlock/service.go

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

fix: Adds lock to prevent data race

---

pkg/secretlock/service.go
test/bdd/features/kms_api.feature
test/bdd/fixtures/kms/docker-compose.yml
test/bdd/fixtures/kms/nginx-config/nginx.conf
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/user.go

perf: horizontal scaling support

---

cmd/kms-rest/startcmd/start.go
cmd/kms-rest/startcmd/start_test.go
pkg/kms/service.go
pkg/kms/service_test.go
pkg/secretlock/service.go
pkg/secretlock/service_test.go

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

fix: Fixes data race

---

docs/design_overview.md

Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

docs: Describe Trustbloc's KMS Server Design

---

cmd/kms-server/go.mod
cmd/kms-server/go.sum
cmd/kms-server/startcmd/params.go
cmd/kms-server/startcmd/start.go
go.mod
go.sum
pkg/secretlock/aws/secret_lock.go
pkg/secretlock/aws/secret_lock_test.go

feat:aws integration

---

go.mod
pkg/secretlock/aws/secret_lock.go
pkg/secretlock/aws/secret_lock_test.go
pkg/secretlock/key/secret_lock.go
pkg/secretlock/key/secret_lock_test.go

refactor: key secret lock and unit tests

refactor: key secret lock and unit tests

---

cmd/kms-server/go.mod
cmd/kms-server/go.sum
cmd/kms-server/startcmd/start.go
go.mod
go.sum
pkg/controller/command/command.go
pkg/controller/command/models.go
pkg/controller/rest/operation.go
pkg/secretlock/shamir/secret_lock_test.go
scripts/generate_test_keys.sh
test/bdd/features/kms_api.feature
test/bdd/fixtures/docker-compose.yml
test/bdd/fixtures/oathkeeper-config/ops-keyserver/rules/resource-server.json
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/kms/auth_edv_steps.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/models.go
test/bdd/pkg/kms/user.go
test/bdd/pkg/kms/zcap.go

test: update bdd tests

---

pkg/controller/command/command.go
pkg/controller/command/command_create_key_store.go
pkg/controller/command/models.go
pkg/controller/rest/models.go
pkg/controller/rest/operation.go
test/bdd/features/kms_api.feature
test/bdd/pkg/keystore/keystore_steps.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/models.go

feat: add compute/verify MAC API

---

pkg/controller/command/command.go
pkg/controller/command/models.go
pkg/controller/rest/models.go
pkg/controller/rest/operation.go

feat: add support for BBS+ crypto API

---

cmd/kms-server/startcmd/start.go
pkg/controller/command/command.go
pkg/controller/command/models.go
pkg/controller/rest/models.go
pkg/controller/rest/operation.go
test/bdd/features/kms_api.feature
test/bdd/features/kms_crypto_box_api.feature
test/bdd/fixtures/oathkeeper-config/auth-keyserver/config.yaml
test/bdd/fixtures/oathkeeper-config/auth-keyserver/rules/resource-server.json
test/bdd/pkg/kms/auth_edv_steps.go
test/bdd/pkg/kms/kms_crypto_box_steps.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/models.go

feat: add crypto box API

---

cmd/kms-server/startcmd/start.go
pkg/controller/mw/zcap_middleware.go
pkg/controller/mw/zcap_middleware_test.go
pkg/controller/rest/actions.go
pkg/controller/rest/handler.go
pkg/controller/rest/operation.go

refactor: decouple zcap middleware from operational rest

---

pkg/controller/command/command.go
pkg/controller/command/models.go
pkg/controller/rest/actions.go
pkg/controller/rest/models.go
pkg/controller/rest/operation.go

feat: key wrapping API

---

test/bdd/features/kms_api.feature
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/models.go
test/bdd/pkg/kms/user.go

test: update BDD tests for key wrapping API (Anoncrypt)

---

test/bdd/features/kms_stress.feature
test/bdd/pkg/internal/bddutil/workerpool.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/stress_steps.go

feat: implement stress test bdd scenario

---

Makefile
test/bdd/features/kms_stress.feature

refactor: separate stress tests from bbd tests

---

Makefile
cmd/kms-server/startcmd/start.go
cmd/kms-server/startcmd/start_test.go

chore: update linter

---

cmd/kms-server/go.mod
cmd/kms-server/go.sum
go.mod
go.sum
pkg/controller/command/command_create_key_store.go
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/models.go
test/bdd/pkg/kms/user.go

fix: integration with EDV

---

Makefile
cmd/kms-server/main.go
pkg/controller/command/command.go
pkg/controller/command/command_create_key_store.go
pkg/controller/rest/operation.go
test/bdd/features/keystore_api.feature
test/bdd/features/kms_api.feature
test/bdd/features/kms_crypto_box_api.feature
test/bdd/features/kms_stress.feature
test/bdd/fixtures/oathkeeper-config/auth-keyserver/rules/resource-server.json
test/bdd/fixtures/oathkeeper-config/ops-keyserver/rules/resource-server.json
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/stress_steps.go

refactor: update REST endpoints

---

.github/workflows/build.yml
.github/workflows/publish.yml

chore: fix image publishing

---

test/bdd/fixtures/aws-config/init/seed.yaml
test/bdd/fixtures/docker-compose.yml

chore: switch to aws-backed key for server's secret lock

---

pkg/controller/command/command.go

fix: small fix of error checks in wrap key command

---

cmd/kms-server/startcmd/params.go
cmd/kms-server/startcmd/start.go
cmd/kms-server/startcmd/start_test.go
test/bdd/fixtures/docker-compose.yml

feat: read aws params from environment variables

---

test/bdd/features/kms_stress.feature
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/stress_steps.go

- read kms server url form env variable.
- separately measure create keystore and create key calls

feat: read kms server url form env variable. 

---

cmd/kms-server/startcmd/start.go
pkg/controller/rest/operation.go

feat: better errors loging

---

cmd/kms-server/startcmd/start.go
pkg/controller/command/command.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/storage/metrics/provider.go
pkg/storage/metrics/provider_test.go
pkg/storage/metrics/store.go
pkg/storage/metrics/store_test.go

feat: added detailed prometheus metrics from sign op

---

cmd/kms-server/startcmd/start.go
pkg/controller/command/command.go
pkg/controller/command/command_create_key_store.go
pkg/controller/command/command_test.go
pkg/controller/command/models.go

test: unit tests for command handlers

---

pkg/controller/command/actions.go
pkg/controller/command/command.go
pkg/controller/command/command_test.go
pkg/controller/command/models.go
pkg/controller/rest/models.go
pkg/controller/rest/operation.go
test/bdd/features/kms_api.feature
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/models.go
test/bdd/pkg/kms/zcap.go

feat: user key rotation

---

Makefile
test/bdd/features/kms_stress.feature
test/bdd/pkg/common/common_steps.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/stress_steps.go

fix: fix stress test to read urls of all services from env variables

---

test/bdd/go.sum

fix: fix stress test go sum error on k8s-deployments

---

test/bdd/bddtests_test.go
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/context/context.go

feat: add the possibility to create bdd context without CA certs path

---

Makefile
test/bdd/features/kms_stress.feature
test/bdd/fixtures/docker-compose.yml
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/stress_steps.go
test/bdd/pkg/kms/user.go

fix: fix stress to fit orb usage scenario(no edv, authzkms and hub-auth)

---

Makefile
test/bdd/bddtests_test.go
test/bdd/features/keystore_api.feature
test/bdd/go.mod
test/bdd/pkg/auth/login.go
test/bdd/pkg/auth/mock_wallet.go
test/bdd/pkg/common/common_steps.go
test/bdd/pkg/context/context.go
test/bdd/pkg/keystore/keystore_steps.go
test/bdd/pkg/kms/auth_edv_steps.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/stress_steps.go

feat: implement stress test bdd scenario for authz + ops kms

---

test/bdd/pkg/auth/login.go
test/bdd/pkg/auth/mock_wallet.go

fix: verbose errors from bdd test login procedure.

---

test/bdd/features/kms_stress.feature
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/stress_steps.go

feat: print avg, min, max durations for kms calls

---

cmd/kms-server/startcmd/start.go
pkg/controller/command/command.go
pkg/controller/command/command_create_key_store.go
pkg/controller/command/command_test.go
pkg/controller/command/models.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/secretlock/aws/secret_lock.go
pkg/secretlock/key/secret_lock.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/stress_steps.go

fix: performance improvements and additional metrics.

---

cmd/kms-server/startcmd/start.go
pkg/controller/command/command.go
pkg/controller/command/command_create_key_store.go

feat: caching support for server's db

---

Makefile

fix: OpenAPI spec generation

---

Makefile
test/bdd/bddtests_test.go
test/bdd/pkg/auth/login.go
test/bdd/pkg/auth/mock_wallet.go
test/bdd/pkg/common/common_steps.go
test/bdd/pkg/context/context.go
test/bdd/pkg/internal/bddutil/workerpool.go
test/bdd/pkg/keystore/keystore_steps.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/models.go
test/bdd/pkg/kms/stress_steps.go
test/bdd/pkg/kms/zcap.go

chore: enable linter and fix found issues for BDD tests

---

Makefile
test/bdd/bddtests_test.go
test/bdd/features/kms_stress.feature
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/stress_steps.go

feat: authz kms stress test.

---

cmd/kms-server/startcmd/params.go
cmd/kms-server/startcmd/start.go
cmd/kms-server/startcmd/start_test.go
pkg/kms/cache/wrap_kms.go
pkg/kms/cache/wrap_kms_test.go

feat: keystore secure cache.

---

cmd/kms-server/startcmd/params.go

fix: enable cache by default.

---

Makefile
test/bdd/features/kms_stress.feature
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/stress_steps.go

feat: ops kms stress test.

---

Makefile
cmd/kms-server/startcmd/params.go
cmd/kms-server/startcmd/start.go
pkg/controller/command/command.go
pkg/controller/command/command_create_key_store.go
pkg/controller/command/command_test.go
pkg/shamir/cache/wrap_provider.go
pkg/shamir/cache/wrap_provider_test.go
pkg/shamir/provider.go
pkg/shamir/provider_test.go
test/bdd/features/kms_stress.feature

feat: shamir secret cache.

---

cmd/kms-server/startcmd/params.go
cmd/kms-server/startcmd/start_test.go

fix: missing shamir params.

---

pkg/controller/mw/zcap_middleware.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go

feat: zcapld metrics.

---

pkg/controller/mw/zcap_middleware.go
pkg/controller/mw/zcap_middleware_test.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go

feat: detailed zcapld metrics.

---

cmd/kms-server/startcmd/start.go

chore: add cache for cors response

---

README.md
docs/use_cases.md

docs: use cases for lock keys

---

pkg/aws/service.go
pkg/aws/service_test.go

feat: add aws service

---

pkg/aws/service.go
pkg/aws/service_test.go

fix: aws service

---

pkg/aws/service.go
pkg/aws/service_test.go

fix: aws get alias

---

.github/workflows/publish.yml

Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

chore: increase publish timeoue for release

---

scripts/generate_test_keys.sh
test/bdd/fixtures/.env
test/bdd/fixtures/docker-compose.yml
test/bdd/fixtures/hydra-config/hydra_configure.sh
test/bdd/fixtures/oidc-config/providers.yaml

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

test: rename hub-auth to auth

---

pkg/aws/service.go
pkg/aws/service_test.go

feat: add HealthCheck method for aws service

---

pkg/aws/service.go
pkg/aws/service_test.go

chore: add health check key

---

pkg/aws/service.go
pkg/aws/service_test.go

fix: aws kms health check

---

.github/workflows/build.yml

chore: update timeout for Publish job

---

pkg/controller/mw/authmw/gnapmw/gnap_middleware.go

chore: disable httpsig verification for GNAP flow

---

pkg/aws/service.go
pkg/aws/service_test.go

chore: support aws create key

---

cmd/kms-server/startcmd/start.go
cmd/kms-server/startcmd/start_test.go

fix: error check during gnap rs client creation

---

cmd/kms-cli/createkeystore/createkeystore.go
test/bdd/bddtests_test.go
test/bdd/features/kms_api.feature
test/bdd/features/kms_crypto_box_api.feature
test/bdd/features/kms_stress.feature
test/bdd/fixtures/.env
test/bdd/fixtures/docker-compose.yml
test/bdd/go.mod
test/bdd/pkg/common/common_steps.go
test/bdd/pkg/context/context.go
test/bdd/pkg/internal/httputil/httputil.go
test/bdd/pkg/kms/auth_edv_steps.go
test/bdd/pkg/kms/kms_steps.go
test/bdd/pkg/kms/models.go
test/bdd/pkg/kms/stress_steps.go
test/bdd/pkg/kms/user.go
test/bdd/pkg/kms/zcap.go

Remove EDV support from KMS BDD tests
Signed-off-by: Yevgen Pukhta <eugene.pukhta@gmail.com>

refactor: Remove EDV from BDD tests

---

Makefile
README.md
cmd/kms-server/go.mod
cmd/kms-server/go.sum
cmd/kms-server/startcmd/start.go
docs/use_cases.md
go.mod
go.sum
pkg/controller/command/actions.go
pkg/controller/command/command.go
pkg/controller/command/command_create_key_store.go
pkg/controller/command/command_test.go
pkg/controller/command/models.go
pkg/controller/rest/models.go
pkg/metrics/metrics.go

Close #326
Signed-off-by: Yevgen Pukhta <eugene.pukhta@gmail.com>

refactor: remove EDV support

---

pkg/aws/service.go
pkg/aws/service_test.go

feat: add CreateAndExportPubKeyBytes func to aws

---

pkg/aws/service.go
pkg/aws/service_test.go

fix: aws kms create method

---

pkg/aws/service.go
pkg/aws/service_test.go

feat: add ECDSASecp256k1IEEEP1363 to aws service

---

pkg/aws/service.go
pkg/aws/service_test.go

fix: send digest msg instead of raw to aws kms

---

pkg/aws/service.go

Signed-off-by: Rajesh Kalaria <rajesh.kalaria@gmail.com>

fix: aws kms key alias validation

---

pkg/aws/service.go

chore: return key alias id

---

pkg/aws/service.go

chore: add alias to key ID when configure

---

pkg/aws/service.go

fix: alias prefix

---

pkg/aws/service.go
pkg/aws/service_test.go

chore: add aws config

---

pkg/aws/service.go

chore: remove get key alias
